name: CI Pipeline

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 🔹 Paso 1: Checkout del repo actual (MyProjectWithCICD, con las pruebas)
      - name: Checkout del repo de pruebas (MyProjectWithCICD)
        uses: actions/checkout@v3

      # 🔹 Paso 2: Clonar el código fuente del otro repo en una subcarpeta
      - name: Clonar código fuente (QA-Automation-Demo)
        uses: actions/checkout@v3
        with:
          repository: daimilamoru/QA-Automation-Demo
          token: ${{ secrets.tokentest }}  # Usa un token personal con permisos de lectura
          path: app-code                         # Se guarda en subcarpeta ./app-code

      # 🔹 Paso 3: Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 🔹 Paso 4: Instalar dependencias del proyecto de pruebas
      - name: Instalar dependencias
        run: npm install

      # 🔹 Paso 5: Instalar navegadores de Playwright
      - name: Instalar Playwright Browsers
        run: npx playwright install --with-deps

      # 🔹 Paso 6: Ejecutar pruebas Smoke
      - name: Ejecutar solo pruebas Smoke
        run: npm test -- tests/smoke
