name: CI Pipeline

# on:
# workflow_dispatch # con esta opcion hay que ejecutarlo manualmente
on:
    push:
      branches:
        - main # Con esta opcion se ejecuta automaticamente 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 🔹 Paso 1: Checkout del repo actual (MyProjectWithCICD, con las pruebas)
      - name: Checkout del repo de pruebas (MyProjectWithCICD)
        uses: actions/checkout@v3

      # 🔹 Paso 2: Clonar el código fuente del otro repo en una subcarpeta
      - name: Clonar código fuente (QA-Automation-Demo)
        uses: actions/checkout@v3
        with:
          repository: daimilamoru/QA-Automation-Demo
          token: ${{ secrets.GITHUB_TOKEN }}  # Usa el token automático de GitHub Actions
          path: app-code                         # Se guarda en subcarpeta ./app-code

      # 🔹 Paso 3: Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 🔹 Paso 4: Instalar dependencias del proyecto de pruebas
      - name: Instalar dependencias
        run: npm install

    # 🔹 Paso 5: Instalar dependencias del proyecto de pruebas

      - name: Otorgar permisos a node_modules/.bin
        run: chmod +x node_modules/.bin/playwright


      # 🔹 Paso 6: Instalar navegadores de Playwright
      - name: Instalar Playwright Browsers
        run: npx --yes playwright install --with-deps

      # 🔹 Paso 7: Ejecutar pruebas Smoke
      - name: Ejecutar solo pruebas Smoke
        run: npx playwright test tests/smoke
