name: Playwright Tests

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3        

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps     

      # - name: Run Playwright tests
      #   run: npx playwright test

      - name: Print environment variables
        run:  printenv | grep -i 'user\|pass'
          # echo "USER=$USER && PASS=$PASS"
        env:
              USER: ${{ secrets.USER }}
              PASS: ${{ secrets.PASS }}

      - name: Check current env
        run: printenv | grep -i 'user\|pass'
            
      - name: Run only smoke tests
        run: npx playwright test tests/smoke
        env:
            USER: ${{ secrets.USER }}
            PASS: ${{ secrets.PASS }}
